### ISSUE TITLE
driver process (ros_main) stops receiving but doesn't actually terminate when it gets signalled SIGINT

### ISSUE THREAD

**Issue by kawk** [PepperlFuchs/pf_lidar_ros2_driver#19]
The driver node (process `ros_main`) only half-heartedly responds to SIGINT. 

**Steps to reproduce the behavior**:
Launch the driver, e.g. craft a `params.yaml` then start the binary directly on command line
```
cat <<EOT > /tmp/params.yaml
killtest:
  ros__parameters:
    transport: "udp"
    scanner_ip: "10.0.10.9"
    max_num_points_scan: 0
    frame_id: "scanner_link"
    device: "R2000"
    start_angle: -1800000
    packet_type: "C"
    scan_topic: "/scan"
    watchdogtimeout: 60000
    watchdog: true
EOT

$WS/install/pf_driver/lib/pf_driver/ros_main --ros-args -r __node:=killtest --params-file /tmp/params.yaml
```

Then try to kill it with Ctrl-C. It will receive SIGINT and change its state, but never terminates:
```
 ^Creceived SIGINT
[INFO] [1733938913.220970697] [killtest]: Device state changed to Initialized
[ERROR] [1733938913.221122614] [killtest]: Network failure
[ERROR] [1733938915.206894965] [transport]: Time out: No packets received in 2 seconds
^Creceived SIGINT
^Creceived SIGINT
^Creceived SIGINT
^Creceived SIGINT
^Creceived SIGINT
```
Although termination is not so important during normal use, it hinders execution of tests that start, stop, re-start the driver...

**Environment**:
Driver 1.3 and 2.0 (e.g. c1a4e12) in ROS Humble, Ubuntu 22.04 LTS
