### ISSUE TITLE
Invalid points in LaserScan aren't handled correctly with "apply_correction"

### ISSUE THREAD

**Issue by kawk** [PepperlFuchs/pf_lidar_ros2_driver#24]
With R2300 4-layer and active "apply_correction", `malloc()` errors occur if the original LaserScan data contains NaN or Inf values. These can occur since #18 which was fixed only a few weeks before.

**To Reproduce**
Prepare R2300 at 10.0.10.76 and start driver with `/tmp/params.yaml` as below
```
ros_main --ros-args -r __node:=ros_main --params-file /tmp/params.yaml
```
```
ros_main:
  ros__parameters:
    transport: "udp"
    scanner_ip: "10.0.10.76"
    max_num_points_scan: 0
    frame_id: "scanner_link"
    start_angle: -450000
    packet_type: "C1"
    scan_topic: "/cloud"
    num_layers: 4
    apply_correction: true
    watchdogtimeout: 60000
    watchdog: false
```

**Symptoms**

As soon as the driver receives scan data from sensor containing invalid values, a `malloc()` error like this will occur:

```
...
[INFO] [1736171940.198833507] [ros_main]: Device state changed to Running
malloc(): corrupted top size
```

Experienced with ROS Humble.
