### ISSUE TITLE
Protocol Error OBD30M-R2000

### ISSUE THREAD

**Issue by Sriramk34** [PepperlFuchs/pf_lidar_ros2_driver#8]
Protocol error while trying to get info of the device. 

**To Reproduce**
1) Connect LiDAR using DHCP and get the IP address
2) Set IP as parameter in config, and set port to 80
3) Launch the R2000.launch file

***YAML Config File***
```yaml
  GNU nano 6.2                                             r2000_params.yaml 
  ros__parameters:
    transport: "udp"
    scanner_ip: "192.168.0.105"
    port: "80"
    device: "R2000"
    start_angle: -1800000
    max_num_points_scan: 0
    packet_type: "C"
    scan_topic: "/pf/scan"
    frame_id: "scanner_link"
    watchdogtimeout: 60000
    watchdog: false
```

**Error**
```
[ros_main-1] protocol error:
[ros_main-1] [ERROR] [1721110425.191788669] [pf_r2000]: Unable to communicate with device. Please check the IP address
[ros_main-1] [ERROR] [1721110425.191834870] [pf_r2000]: Unable to initialize device
[ros_main-1] terminate called without an active exception
[ERROR] [ros_main-1]: process has died [pid 2911, exit code -6, cmd '/home/pf_ws/pf_lidar_ros2_driver/install/pf_driver/lib/pf_driver/ros_main --ros-args -r __node:=pf_r2000 --params-file /home/pf_ws/pf_lidar_ros2_driver/install/pf_driver/share/pf_driver/config/r2000_params.yaml'].
```

**Expected behavior**
Connection to be made and receive LiDAR data from the sensor. 

**Environment**
 - OS:  Ubuntu 22.04 LTS
 - ROS Version: ROS2 Humble

**Sensor**
 - Device:  OBD30M-R2000
 - FW Version: - 1.62 (From PactWare)
 - HW Version: - 1.72 (From PactWare)
 
_Obtain FW/HW version via_ `curl 'http://<Sensor_IP_here>/cmd/get_parameter?list=revision_fw;revision_hw'
Error 404: Not Found
File not found 
Error when trying to obtain firmware information.
